name: Release
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'

env:
  NODE_VERSION: 20.5.1
  PNPM_VERSION: 8.7.5

jobs:
  prepare:
    if: contains(github.event.head_commit.message , 'chore(release)') == false
    runs-on: ubuntu-22.04
    steps:
      - name: GIT – Checkout
        uses: actions/checkout@v4
      - name: .npmrc
        run: echo "link-workspace-packages=false" > .npmrc
      - name: PNPM – Install
        uses: lskjs/action-pnpm@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
          pnpm-version: ${{ env.PNPM_VERSION }}
  build:
    needs: [prepare]
    runs-on: ubuntu-22.04
    steps:
      - name: GIT – Checkout
        uses: actions/checkout@v4
      - name: .npmrc
        run: echo "link-workspace-packages=false" > .npmrc
      - name: PNPM – release
        uses: lskjs/action-pnpm@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
          pnpm-version: ${{ env.PNPM_VERSION }}
          command: |
            pnpm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}" && \
            pnpm release --yes
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: NPM - get new version
        run: echo PACKAGE_VERSION=$(node -p "require('./package.json').version") >> $GITHUB_ENV
      - name: Commit version and tag to git
        uses: EndBug/add-and-commit@v9
        with:
          add: 'package.json'
          author_name: Igor Suvorov Bot
          author_email: bot@isuvorov.com
          default_author: github_actor
          message: 'chore(release): 🎉 v${{ env.PACKAGE_VERSION }}'
          tag: 'v${{ env.PACKAGE_VERSION }} --force'
